### ISSUE TITLE
XLabs Launcher unable to find repo

### ISSUE THREAD

**Issue by Richugireesh** [XLabsProject/iw4x-rawfiles#33]
![image](https://user-images.githubusercontent.com/86412885/186733647-c3bbb8f6-1679-409d-a2bf-2ca2b67cbc27.png)

**Comment by Dss0** [comment]
This has nothing to do with the rawfiles, the download itself works fine. Could be because you have special characters in your windows username/the filepath to your game folder or your connection is unstable.
