### ISSUE TITLE
Slow download from github cdn

### ISSUE THREAD

**Issue by woodybriggs** [XLabsProject/iw4x-rawfiles#35]
Github's release CDN for built artifacts can be very slow for users to download via the launcher or directly from github. 

Explore hosting this on a wider CDN like AWS with cloudfront and S3 (or even torrent) for faster downloads across the globe

![image](https://user-images.githubusercontent.com/15181066/200752694-2f8d49d8-e3cd-40d9-bfc6-3565c310309a.png)

![image](https://user-images.githubusercontent.com/15181066/200752794-8573a718-3938-4c46-8d66-0d245971f3d5.png)

**Comment by diamante0018** [comment]
Wait faster for download to finish, easy solution
